### ISSUE TITLE
Can't compress a recycled bitmap

### ISSUE THREAD

**Issue by renaldi2108** [cosee/native_image_cropper#104]
<img width="1228" alt="Screenshot 2024-07-29 at 13 12 49" src="https://github.com/user-attachments/assets/b4f9b236-6372-453c-b55a-9795664bf25f">

This case occurs when the drag point is not moved at all / there is no change in the drag point and the _**await _cropController.crop()**_ function is immediately called.

you can try the solution here https://stackoverflow.com/questions/8490474/cant-compress-a-recycled-bitmap

**Comment by quoc-huynh-cosee** [comment]
I'm currently buse and will look into it if I have time.
Feel free to open a PR :)

**Comment by renaldi2108** [comment]
Alright, I will test it again and then create a pull request on this repo. Thank you for allowing me to submit a pull request for this open-source project. I hope it can help the team and other developers who use it.

**Comment by renaldi2108** [comment]
> I'm currently buse and will look into it if I have time. Feel free to open a PR :)

Alright, I will test it again and then create a pull request on this repo. Thank you for allowing me to submit a pull request for this open-source project. I hope it can help the team and other developers who use it.

**Comment by quoc-huynh-cosee** [comment]
@renaldi2108 Can you try out
```yaml
  native_image_cropper_android:
    git:
      url: https://github.com/cosee/native_image_cropper.git
      path: native_image_cropper_android
      ref: fix/recycled-bitmap
  ```
and check if your issue is resolved with this change?
