### ISSUE TITLE
Cropped image is rotated

### ISSUE THREAD

**Issue by DAIHUISENNB** [cosee/native_image_cropper#82]

**Comment by quoc-huynh-cosee** [comment]
@DAIHUISENNB Can you describe your issue in English please?

**Comment by DAIHUISENNB** [comment]
After using NativeImageCropper.cropRect on some Android phones, the image will rotate counterclockwise by 90 degrees。
I checked and found out that the problem lies in the getCroppedRectBitmap method
![image](https://github.com/cosee/native_image_cropper/assets/49010755/89a739bd-1ff9-4935-83a0-5c2bef25c929)
This piece of code！

**Comment by DAIHUISENNB** [comment]
need to determine the Exif information of the image, that's how I solved it
![image](https://github.com/cosee/native_image_cropper/assets/49010755/99ce658c-2476-4ca6-968b-bd1845201b6a)

**Comment by DAIHUISENNB** [comment]
@quoc-huynh-cosee

**Comment by quoc-huynh-cosee** [comment]
Great catch! Didn't know about that, I'll fix this asap.

**Comment by quoc-huynh-cosee** [comment]
@DAIHUISENNB Can you please check if your issue resolves by adding this to your pubspec.yaml?

```yaml
native_image_cropper:
  git:
    url: https://github.com/cosee/native_image_cropper.git
    path: native_image_cropper
    ref: fix/wrong-rotation-after-crop
```
